version: '1.0'

services:
  backend:
    container_name: registera-backend    
    build: .    
    ports:
      - "5000:5000"
    links:
     - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"